In [2]:
import sys; sys.path.insert(0,'..')
from prosodic import *

In [3]:
s="Of man's first disobedience, and the fruit"

In [4]:
line = Line(s)
line

Line(num=1, txt="Of man's first disobedience, and the fruit")

In [5]:
parses = line.parse()
parse = parses[0]
parse.attrs

{'line_num': 1,
 'line_txt': "Of man's first disobedience, and the fruit",
 'txt': "of MAN'S first DI so BE dien CE and.the FRUIT",
 'rank': 1,
 'meter': '-+-+-+-+--+',
 'stress': '-+++-+----+',
 'score': 2,
 'is_bounded': 0}

In [6]:
parses.df_syll

                                                                                                                                                                               parselist_num_parses  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress meterpos_num meterpos_val meterslot_num
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+  1            w            1                                 1
                                                                                                                                      2            s            2                                 1
                                                                                                                                      3            w            3                                 1
                                                                                                                                      4            s            4                                 1
                                                                                                                                      5            w            5                                 1
                                                                                                                                      6            s            6                                 1
                                                                                                                                      7            w            7                                 1
                                                                                                                                      8            s            8                                 1
                                                                                                                                      9            w            9                                 1
                                                                                                                                                                10                                1
                                                                                                                                      10           s            11                                1
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+  1            w            1                                 1
                                                                                                                                      2            s            2                                 1
                                                                                                                                      3            w            3                                 1
                                                                                                                                      4            s            4                                 1
                                                                                                                                      5            w            5                                 1
                                                                                                                                      6            s            6                                 1
                                                                                                                                      7            w            7                                 1
                                                                                                                                      8            s            8                                 1
                                                                                                                                      9            w            9                                 1
                                                                                                                                      10           s            10                                1
                                                                                                                                      11           w            11                                1

                                                                                                                                                                               parselist_num_all_parses  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress meterpos_num meterpos_val meterslot_num
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+  1            w            1                                     2
                                                                                                                                      2            s            2                                     2
                                                                                                                                      3            w            3                                     2
                                                                                                                                      4            s            4                                     2
                                                                                                                                      5            w            5                                     2
                                                                                                                                      6            s            6                                     2
                                                                                                                                      7            w            7                                     2
                                                                                                                                      8            s            8                                     2
                                                                                                                                      9            w            9                                     2
                                                                                                                                                                10                                    2
                                                                                                                                      10           s            11                                    2
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+  1            w            1                                     2
                                                                                                                                      2            s            2                                     2
                                                                                                                                      3            w            3                                     2
                                                                                                                                      4            s            4                                     2
                                                                                                                                      5            w            5                                     2
                                                                                                                                      6            s            6                                     2
                                                                                                                                      7            w            7                                     2
                                                                                                                                      8            s            8                                     2
                                                                                                                                      9            w            9                                     2
                                                                                                                                      10           s            10                                    2
                                                                                                                                      11           w            11                                    2

                                                                                                                                                                               parse_score  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress meterpos_num meterpos_val meterslot_num
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+  1            w            1                        2
                                                                                                                                      2            s            2                        2
                                                                                                                                      3            w            3                        2
                                                                                                                                      4            s            4                        2
                                                                                                                                      5            w            5                        2
                                                                                                                                      6            s            6                        2
                                                                                                                                      7            w            7                        2
                                                                                                                                      8            s            8                        2
                                                                                                                                      9            w            9                        2
                                                                                                                                                                10                       2
                                                                                                                                      10           s            11                       2
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+  1            w            1                        4
                                                                                                                                      2            s            2                        4
                                                                                                                                      3            w            3                        4
                                                                                                                                      4            s            4                        4
                                                                                                                                      5            w            5                        4
                                                                                                                                      6            s            6                        4
                                                                                                                                      7            w            7                        4
                                                                                                                                      8            s            8                        4
                                                                                                                                      9            w            9                        4
                                                                                                                                      10           s            10                       4
                                                                                                                                      11           w            11                       4

                                                                                                                                                                               parse_is_bounded  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress meterpos_num meterpos_val meterslot_num
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+  1            w            1                             0
                                                                                                                                      2            s            2                             0
                                                                                                                                      3            w            3                             0
                                                                                                                                      4            s            4                             0
                                                                                                                                      5            w            5                             0
                                                                                                                                      6            s            6                             0
                                                                                                                                      7            w            7                             0
                                                                                                                                      8            s            8                             0
                                                                                                                                      9            w            9                             0
                                                                                                                                                                10                            0
                                                                                                                                      10           s            11                            0
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+  1            w            1                             1
                                                                                                                                      2            s            2                             1
                                                                                                                                      3            w            3                             1
                                                                                                                                      4            s            4                             1
                                                                                                                                      5            w            5                             1
                                                                                                                                      6            s            6                             1
                                                                                                                                      7            w            7                             1
                                                                                                                                      8            s            8                             1
                                                                                                                                      9            w            9                             1
                                                                                                                                      10           s            10                            1
                                                                                                                                      11           w            11                            1

                                                                                                                                                                               meterpos_num_slots  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress meterpos_num meterpos_val meterslot_num
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+  1            w            1                               1
                                                                                                                                      2            s            2                               1
                                                                                                                                      3            w            3                               1
                                                                                                                                      4            s            4                               1
                                                                                                                                      5            w            5                               1

In [16]:
parses.df

                                                                                                                                       parse_score  parse_is_bounded  meterpos_num_slots  *w_peak  \
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+           2.0               0.0                  13        0
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+           4.0               1.0                  11        0

                                                                                                                                       *w_stress  *s_unstress  *unres_across  *unres_within
line_num line_txt                                   parse_rank parse_txt                                     parse_meter parse_stress
1        Of man's first disobedience, and the fruit 1          of MAN'S first DI so BE dien CE and.the FRUIT -+-+-+-+--+ -+++-+----+           1            1              0              0
                                                    2          of MAN'S first DI so BE dien CE and THE fruit -+-+-+-+-+- -+++-+----+           2            2              0              0

In [8]:
res=line.parse()

In [9]:
parse = res[0]
# parse

In [10]:
[slot.wordtoken for slot in parse.slots]

[None, None, None, None, None, None, None, None, None, None, None]

In [11]:
type(parse.line), type(line)

(prosodic.lines.Line, prosodic.lines.Line)

In [12]:
line.attrs

{'num': 1, 'txt': "Of man's first disobedience, and the fruit"}

In [13]:
parse1 = line.parses[0]
parse1

AttributeError: 'Line' object has no attribute 'best_parse'

In [ ]:
parse2 = line.parses[1]
parse2

Parse(txt="of MAN'S first DI so BE dien.ce AND the FRUIT", rank=2, meter='-+-+-+--+-+', stress='-+++-+----+', score=3, is_bounded=1)

In [ ]:
parse1.bounds(parse2)

True

In [ ]:
random.choice(line.parses)

Parse(txt="OF.MAN'S first.di SO be.dien CE and.the FRUIT", rank=212, meter='++--+--+--+', stress='-+++-+----+', score=12, is_bounded=1)